exit when subscripts are unavaible

diff --git a/files/bin/fnetstat b/files/bin/fnetstat
--- a/files/bin/fnetstat
+++ b/files/bin/fnetstat
@@ -15,13 +15,16 @@ WIFI_FILENAME="fnetstat_wifi"
 mkdir -p $BACKUP_FOLDER
 
 if [ ! -f $MINUTLY ]; then
-  echo "$MINUTLY-Script was not found"
+	echo "$MINUTLY-Script was not found"
+	exit 2
 fi
 if [ ! -f $DAILY ]; then
 	echo "$DAILY-Script was not found"
+	exit 2
 fi
 if [ ! -f $WIFISCAN ]; then
 	echo "$WIFISCAN-Script was not found"
+	exit 2
 fi
 
 if [ $# -eq 1 ]; then
